### ISSUE TITLE
Calling a handler that does not exist does not throw any errors for nanobus.filter.session/v1 filter

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wasmflow#96]
**Describe the bug**

I was using the `nanobus.filter.session/v1 filter` and I had the `handler` referencing a handler name that does not exist.  Nanobus did not complain or let me know in any way that the handler does not exist.  It just failed silently.

**To Reproduce**
Incorrect Handler name:
```
filters:
  - uses: nanobus.filter.session/v1
    with:
      handler: "security::getAccessToken"

...

interfaces:
  sso.Sessions:
    getTenant:
      steps:
        - name: get tenant_id from sid
          uses: "@postgres/query"
          with:
            resource: ssodb

```

**Actual behavior**

There is no error.  I just does not execute.

**Expected behavior**

I would expect some type of error or log to occur to let me know that the called handler does not exist.

**Environment (where applicable):**

- OS: OSX
- Architecture: M1/ARM
- Build Version: 0.0.10

**Additional context** Add any other context about the problem here.
